-- CPFs used in this test were generated by the tool on website https://www.4devs.com.br/gerador_de_cpf

insert into "user" (id, created_at, updated_at, version, email, name, cpf, birthday_date, password) values (10, now(), now(), 0, 'test1@test.com', 'Test One', '05155638038', '1999-01-20', 'somepassword');
insert into "user" (id, created_at, updated_at, version, email, name, cpf, birthday_date, password) values (20, now(), now(), 0, 'test2@test.com', 'Test Two', '92158444061', '1999-08-18', 'somepassword');
insert into "user" (id, created_at, updated_at, version, email, name, cpf, birthday_date, password) values (30, now(), now(), 0, 'test3@test.com', 'Test Three', '59029991038', '1992-02-08', 'somepassword');
insert into "user" (id, created_at, updated_at, version, email, name, cpf, birthday_date, password) values (40, now(), now(), 0, 'test4@test.com', 'Test Four', '85387931010', '2006-05-26', 'somepassword');
insert into "user" (id, created_at, updated_at, version, email, name, cpf, birthday_date, password) values (50, now(), now(), 0, 'test5@test.com', 'Test Five', '80939033054', '1982-08-18', 'somepassword');
insert into "user" (id, created_at, updated_at, version, email, name, cpf, birthday_date, password) values (60, now(), now(), 0, 'test6@test.com', 'Test Six', '60936549076', '1995-01-01', 'somepassword');

insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (8, now(), now(), 0, '5336139285539458', '01/24', 421, 'Test One', 10);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (9, now(), now(), 0, '5336139285539459', '02/24', 422, 'Test Two', 10);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (10, now(), now(), 0, '5336139285539460', '03/24', 423, 'Test Three', 10);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (11, now(), now(), 0, '5336139285539461', '04/24', 424, 'Test Four', 10);

insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (12, now(), now(), 0, '5336139285539462', '05/24', 425, 'Test Five', 20);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (13, now(), now(), 0, '5336139285539463', '06/24', 426, 'Test Six', 20);

insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (14, now(), now(), 0, '5336139285539464', '07/24', 427, 'Test Seven', 30);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (15, now(), now(), 0, '5336139285539465', '08/24', 428, 'Test Eight', 30);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (16, now(), now(), 0, '5336139285539466', '09/24', 429, 'Test Nine', 30);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (17, now(), now(), 0, '5336139285539467', '10/24', 430, 'Test Ten', 30);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (18, now(), now(), 0, '5336139285539468', '11/24', 431, 'Test Eleven', 30);

insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (19, now(), now(), 0, '5336139285539469', '12/24', 432, 'Test Twelve', 40);
insert into user_payment_card (id, created_at, updated_at, version, card_number, expiring_date, cvv, custom_name, user_id) values (20, now(), now(), 0, '5336139285539470', '01/25', 433, 'Test Thirteen', 40);

